name: CynthiaLarner-Cooper
favicon: null
layout_spectrum: 0.5507388468831778
typography_spectrum: 0.022615985944867134
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#424a19'
    - '#170805'
    - '#ede9e6'
    - '#b0b165'
    - '#701c00'
  brandStrength: 0.875
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
