name: CynthiaLarner-Cooper
favicon: null
layout_spectrum: 0.9398
typography_spectrum: 0.77398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8ab68'
    - '#985a27'
    - '#190e08'
    - '#e1831a'
    - '#ebe4cc'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
